;;; early-init.el --- Generated Emacs Hypervisor early init -*- lexical-binding: t; -*-

;; emacs-hypervisor-generated: t
;; This file was generated by `emacs-hypervisor init'.
;; User-owned early startup code lives in the Hypervisor config directory.

(setq package-user-dir (expand-file-name "packages/" user-emacs-directory))

(defvar emacs-hypervisor-early-init-error nil
  "Error message from loading the user-owned early-init file, or nil.
Recorded here so the session startup can surface it as a warning; an
error in user early-init must not crash the trusted stage.")

;; XDG resolution is duplicated from home-startup.el's
;; `emacs-hypervisor--xdg-config-home' because this file runs before the
;; kernel loads; keep the two in sync.
(let* ((xdg-config-home (getenv "XDG_CONFIG_HOME"))
       (config-base
        (if (and xdg-config-home (not (equal xdg-config-home "")))
            xdg-config-home
          "~/.config"))
       (hypervisor-config-directory
        (expand-file-name "emacs-hypervisor" config-base))
       (user-early-init
        (expand-file-name "early-init.el" hypervisor-config-directory)))
  (when (file-exists-p user-early-init)
    (condition-case err
        (load user-early-init nil t)
      (error
       (setq emacs-hypervisor-early-init-error
             (format "user early-init failed: %s: %s"
                     user-early-init (error-message-string err)))
       (message "[Hypervisor] %s" emacs-hypervisor-early-init-error)))))
