;;; early-init.el --- Generated Emacs Hypervisor early init -*- lexical-binding: t; -*-

;; emacs-hypervisor-generated: t
;; This file was generated by `emacs-hypervisor init'.
;; User-owned early startup code lives in the Hypervisor config directory.

(let* ((xdg-config-home (getenv "XDG_CONFIG_HOME"))
       (config-base
        (if (and xdg-config-home (not (equal xdg-config-home "")))
            xdg-config-home
          "~/.config"))
       (hypervisor-config-directory
        (expand-file-name "emacs-hypervisor" config-base))
       (user-early-init
        (expand-file-name "early-init.el" hypervisor-config-directory)))
  (when (file-exists-p user-early-init)
    (load user-early-init nil t)))
